### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nopnop2002** [TaraHoleInIt/tarablessd1306#3]
I tried installation of your product.
But an error occurred by a build.

	git clone --recursive https://github.com/TaraHoleInIt/tarablessd1306_examples

	cd tarablessd1306_examples/

	cd HelloWorld/

	rm sdkconfig.*

	make menuconfig

	make

	Generating esp32.project.ld
	LD build/tarablessd1306_helloworld.elf
	/home/robotics/tarablessd1306_examples/HelloWorld/build/main/libmain.a(main.o):(.literal.DefaultBusInit+0x20): undefined reference to `SSD1306_I2CMasterInitDefault'
	/home/robotics/tarablessd1306_examples/HelloWorld/build/main/libmain.a(main.o):(.literal.DefaultBusInit+0x24): undefined reference to `SSD1306_I2CMasterAttachDisplayDefault'
	/home/robotics/tarablessd1306_examples/HelloWorld/build/main/libmain.a(main.o):(.literal.DefaultBusInit+0x28): undefined reference to `SSD1306_SPIMasterInitDefault'
	/home/robotics/tarablessd1306_examples/HelloWorld/build/main/libmain.a(main.o):(.literal.DefaultBusInit+0x2c): undefined reference to `SSD1306_SPIMasterAttachDisplayDefault'
	/home/robotics/tarablessd1306_examples/HelloWorld/build/main/libmain.a(main.o): In function `DefaultBusInit':
	/home/robotics/tarablessd1306_examples/HelloWorld/main/main.c:42: undefined reference to `SSD1306_I2CMasterInitDefault'
	/home/robotics/tarablessd1306_examples/HelloWorld/main/main.c:43: undefined reference to `SSD1306_I2CMasterAttachDisplayDefault'
	/home/robotics/tarablessd1306_examples/HelloWorld/main/main.c:43: undefined reference to `SSD1306_SPIMasterInitDefault'
	/home/robotics/tarablessd1306_examples/HelloWorld/main/main.c:48: undefined reference to `SSD1306_SPIMasterAttachDisplayDefault'
	collect2: error: ld returned 1 exit status
	/home/robotics/esp-idf/make/project.mk:517: recipe for target '/home/robotics/tarablessd1306_examples/HelloWorld/build/tarablessd1306_helloworld.elf' failed
	make: *** [/home/robotics/tarablessd1306_examples/HelloWorld/build/tarablessd1306_helloworld.elf] Error 1

There is default_if_i2c.c.

	$ grep -r SSD1306_I2CMasterInitDefault *
	components/tarablessd1306/ifaces/default_if_i2c.c:bool SSD1306_I2CMasterInitDefault( void ) {
	components/tarablessd1306/ssd1306_default_if.h:bool SSD1306_I2CMasterInitDefault( void );
	main/main.c:        assert( SSD1306_I2CMasterInitDefault( ) == true );

archive is:

	/tarablessd1306_examples/HelloWorld/build/tarablessd1306$ ar tv libtarablessd1306.a
	rw-rw-r-- 1000/1000  50236 Apr 18 11:25 2019 ssd1306_font.o
	rw-rw-r-- 1000/1000  55712 Apr 18 11:25 2019 ssd1306.o
	rw-rw-r-- 1000/1000  36044 Apr 18 11:25 2019 ssd1306_draw.o
	rw-rw-r-- 1000/1000  13624 Apr 18 11:25 2019 font_droid_sans_fallback_15x17.o
	rw-rw-r-- 1000/1000  12244 Apr 18 11:25 2019 font_droid_sans_mono_13x24.o
	rw-rw-r-- 1000/1000  18740 Apr 18 11:25 2019 font_liberation_mono_17x30.o
	rw-rw-r-- 1000/1000  17844 Apr 18 11:25 2019 font_droid_sans_mono_16x31.o
	rw-rw-r-- 1000/1000   8472 Apr 18 11:25 2019 font_droid_sans_fallback_11x13.o
	rw-rw-r-- 1000/1000   7532 Apr 18 11:25 2019 font_liberation_mono_9x15.o
	rw-rw-r-- 1000/1000  12244 Apr 18 11:25 2019 font_liberation_mono_13x21.o
	rw-rw-r-- 1000/1000  25048 Apr 18 11:25 2019 font_droid_sans_fallback_24x28.o
	rw-rw-r-- 1000/1000   6636 Apr 18 11:25 2019 font_droid_sans_mono_7x13.o
	rw-rw-r-- 1000/1000   2024 Apr 18 11:25 2019 default_if_spi.o
	rw-rw-r-- 1000/1000   2024 Apr 18 11:25 2019 default_if_i2c.o

 
Advice, please.

**Comment by TaraHoleInIt** [comment]
I think I know what this is.
Those default interfaces need to be enabled in menuconfig in the components section.

Let me know if that works.

**Comment by nopnop2002** [comment]
Thank you for response.
I made enable default interfaces using menuconfig.
build is success.
Please comment how to build in README.md.

![config-1](https://user-images.githubusercontent.com/6020549/56450496-ad2e9700-6361-11e9-8f6c-db40f45578e0.jpg)
![config-2](https://user-images.githubusercontent.com/6020549/56450500-b3247800-6361-11e9-937a-e8a0b7b33822.jpg)

Thank you for share your code.

**Comment by GothAck** [comment]
Having similar issues with the latest esp-idf here, it seems the component is not built or linked by cmake, even though the include dir is respected
