### ISSUE TITLE
SSD1306_Clear Causes SSD1306_Update to draw 8 Horizontal Lines

### ISSUE THREAD

**Issue by JayEnaR** [TaraHoleInIt/tarablessd1306#5]
I've tried using two separate 128x64/0.96" SSD1306 OLED displays and both yield the same result. 
I'm using ESP-IDF v4.0 and HelloWorld tarablessd1306_examples component. Any ideas what's  causing this? When `SSD1306_Clear` is not called, the lines aren't drawn, but clearing and then updating draws these 8 unwanted horizontal lines.

None of the `SSD1306_DrawLine` functions are being called.
![Screenshot_20191021-212407_Gallery](https://user-images.githubusercontent.com/25684062/67236303-4fcaee00-f449-11e9-887a-9126f3b405bf.jpg)

**Comment by TaraHoleInIt** [comment]
I'll look into this when I can today or tomorrow but an immediate change you can test is changing SSD1306_I2C_COMMAND_MODE in default_if_i2c.c from 0x80 to 0 since that is very wrong.

**Comment by JayEnaR** [comment]
> I'll look into this when I can today or tomorrow but an immediate change you can test is changing SSD1306_I2C_COMMAND_MODE in default_if_i2c.c from 0x80 to 0 since that is very wrong.

Well that did the trick! Thanks
