### ISSUE TITLE
Unable to Flip Vertically

### ISSUE THREAD

**Issue by JayEnaR** [TaraHoleInIt/tarablessd1306#6]
I set the `SSD1306_SetVFlip `and `SSD1306_SetHFlip `to flip the screen content, whereas standard, everything seems upside-down. The `SSD1306_SetHFlip `works fine but the `SSD1306_SetVFlip `does not flip vertically. Any Ideas?

Using ESP-IDF v4.0 and the _HelloWorld_ _tarablessd1306_examples_ component

**Comment by TaraHoleInIt** [comment]
Hm.
I'll have to get my esp32 dev setup back up to debug this when I get the chance hopefully soon.

In the meantime you can try changing COM_Pins_Alternative to COM_Pins_Sequential at
https://github.com/TaraHoleInIt/tarablessd1306/blob/master/ssd1306.c#L218

**Comment by JayEnaR** [comment]
Fixed it by setting `SSD1306_SetHFlip` true; `SSD1306_SetVFlip` false; and `COM_ScanDir_RL`
Thanks for the tip.
